stages:
  - build
  - migrate
  - review
  - review_preprod
  - deploy
  - sentry

# Variables to be set on group / project in gitlab variables:

# CI_DOMAIN
# CI_TOOLS_REPOSITORY_URL
# SENTRY_DSN

before_script:
  - rm -rf bin
  - git clone $CI_TOOLS_REPOSITORY_URL -b new-infra bin/
  - export PATH=$PATH:${PWD}/bin
  - export BUILD_NAME=${CI_PROJECT_NAME}-${CI_MERGE_REQUEST_IID:-preprod}
  - export DOMAIN="${CI_PROJECT_NAME}_${CI_MERGE_REQUEST_IID:-preprod}.${CI_DOMAIN}"
  - export COMPOSE_PROJECT_NAME=${BUILD_NAME}
  - cp .env-ci .env
  - echo "UID=`id -u`" >> .env
  - sops -d ci.secrets.docker-compose.yml > secrets.docker-compose.yml

clean-docker:
  stage: build
  script:
    - docker system prune -f
  when: manual

build:
  stage: build
  before_script:
    - sudo CI_PIPELINE_ID=$CI_PIPELINE_ID CI_PROJECT_NAME=$CI_PROJECT_NAME CI_REPOSITORY_URL=$CI_REPOSITORY_URL ~/prepare_btrfs.sh
    # do it twice because before_script is redefined
    - export BUILD_NAME=${CI_PROJECT_NAME}-${CI_MERGE_REQUEST_IID:-preprod}  
    - export DOMAIN="${CI_PROJECT_NAME}_${CI_MERGE_REQUEST_IID:-preprod}.${CI_DOMAIN}"
    - export COMPOSE_PROJECT_NAME=${BUILD_NAME}
    - cp .env-ci .env
    - sops -d ci.secrets.docker-compose.yml > secrets.docker-compose.yml
  script:
    - cd odoo && ak clone && ak sparse && ak build && cd ..
    - DOCKER_BUILDKIT=1 docker-compose build
  after_script:
    - sudo CI_PIPELINE_ID=$CI_PIPELINE_ID CI_PROJECT_NAME=$CI_PROJECT_NAME ~/cleanup_btrfs.sh
  only:
    - merge_requests
    - "master"
    - "main"

migrate:
  stage: migrate
  script:
    - docker-compose kill
    #- echo $CI_MERGE_REQUEST_LABELS | grep keepdb || ci-getdb
    - sops -d ci-db-token > ci-db-token.env && set -o allexport; source ./ci-db-token.env; set +o allexport; ci-getdb

    # ci-getdevdb pour avoir une base vierge
    - docker-compose run odoo gosu odoo click-odoo-update
  only:
    - merge_requests
    - "master"
    - "main"

review:
  stage: review
  script:
    - docker-compose up -d
  environment:
    name: test/${CI_PROJECT_NAME}-${CI_MERGE_REQUEST_IID}
    url: https://${DOMAIN}
    on_stop: stop_review
  only:
    - merge_requests

stop_review:
  stage: review
  script:
    - docker-compose down --rmi local --volumes
  environment:
    name: test/${CI_PROJECT_NAME}-${CI_MERGE_REQUEST_IID}
    action: stop
  when: manual
  only:
    - merge_requests

review_preprod:
  stage: review_preprod
  script:
    - ci-getdb
    - docker-compose up -d
  environment:
    name: preprod
    url: https://${CI_PROJECT_NAME}_preprod.${CI_DOMAIN}
  only:
    - "14.0"
    - "master"
    - "main"

deploy:
  stage: deploy
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    # push to repository with :branchname and :commit
    - docker tag $BUILD_NAME $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    - docker tag $BUILD_NAME $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  when: manual
  only:
    - "14.0"
    - "master"
    - "main"

sentry:
  stage: sentry
  image:
    name: getsentry/sentry-cli
    entrypoint: [""]
  script:
    - env | grep SENTRY > sentry.env
    - docker run --env-file sentry.env getsentry/sentry-cli info
    - export PWD=`pwd`
    - echo $PWD
    - docker run --env-file sentry.env -v $PWD:/work  getsentry/sentry-cli releases new $CI_COMMIT_SHORT_SHA --finalize
    - docker run --env-file sentry.env -v $PWD:/work  getsentry/sentry-cli releases set-commits $CI_COMMIT_SHORT_SHA --auto
  only:
    - "14.0"
    - "master"
    - "main"
  needs:
    - deploy