services:
  mailhog:
    # TODO we should take a look to this
    # https://github.com/axllent/mailpit
    # it support smtp auth
    image: mailhog/mailhog
    container_name: "mailhog"
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mailhog.rule=Host(`${CI_PROJECT_NAME}_mailhog.${CI_DOMAIN}`)"
      - "traefik.http.routers.mailhog.tls=false"
      - "traefik.http.routers.mailhog.service=mailhog"
      - "traefik.http.services.mailhog.loadbalancer.server.port=8025"
      - "traefik.http.routers.mailhog.middlewares=mailhog"
      # Note: when used in docker-compose.yml all dollar signs in the hash need to be doubled for escaping.
      # To create user:password pair, it's possible to use this command:
      # echo $(htpasswd -nB admin) | sed -e s/\\$/\\$\\$/g
      - "traefik.http.middlewares.mailhog.basicauth.users=admin:${MAIL_CI_PASS}"
    ports:
      - 10.10.10.207:1025:1025
  odoo:
    build:
      context: ./odoo
      target: prod
    image: "${BUILD_NAME}"
    environment:
      ODOO_BASE_URL: https://${DOMAIN}
      ODOO_REPORT_URL: http://ci-${BUILD_NAME}:8069
      #SENTRY: True TODO FIXME
      PGSSLMODE: require
      PGDATABASE: $DB_NAME
      PGHOST: $PGHOST
      PGPASSWORD: $PGPASSWORD
      PGUSER: $PGUSER
      # TODO discuss if we want/need to have a "ci" running env
      RUNNING_ENV: preprod
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls=false"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-long.rule=Host(`${DOMAIN}`) &&
        PathPrefix(`/longpolling/`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-long.tls=false"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.service=${COMPOSE_PROJECT_NAME}odoo"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-long.service=${COMPOSE_PROJECT_NAME}odoo_long"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}odoo.loadbalancer.server.port=8069"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}odoo_long.loadbalancer.server.port=8072"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}middle.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.middlewares=${COMPOSE_PROJECT_NAME}middle"
    networks:
      - traefik
    volumes:
      - type: tmpfs
        target: /data/odoo
      - type: volume
        source: filestore
        target: /data/odoo/filestore
      - type: bind
        source: ./shared
        target: /shared
volumes:
  filestore:
networks:
  traefik:
    external: true
version: "3.7"
