version: "3.7"
networks:
  local:
  traefik:
    external: true
services:
  db:
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_DB=db
    image: quay.io/akretion/postgresql:10
    volumes:
      - .db/:/var/lib/postgresql/data
    networks:
      - local
  odoo:
    build: odoo
    environment:
      - DEMO=True
      - MARABUNTA_MODE=demo
      - DB_HOST=db
      - DB_USER=odoo
      - DB_PASS=odoo
      - DB_NAME=db

      # you can specify your own addons path, if you don't want to use links
      # - ADDONS_PATH=/odoo/links,/odoo/local-src,/odoo/src/odoo/addons,/odoo/src/addons,/odoo/external-src/server-tools
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${COMPOSE_PROJECT_NAME}.localhost`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-long.rule=Host(`${COMPOSE_PROJECT_NAME}.localhost`) && PathPrefix(`/longpolling/`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.service=${COMPOSE_PROJECT_NAME}odoo"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-long.service=${COMPOSE_PROJECT_NAME}odoo_long"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}odoo.loadbalancer.server.port=8069"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}odoo_long.loadbalancer.server.port=8072"
      - "docky.help=http://${COMPOSE_PROJECT_NAME}.localhost"
    volumes:
      - ./odoo/local-src:/odoo/local-src
      - ./odoo/external-src:/odoo/external-src
      - ./odoo/src:/odoo/src
      - ./odoo/links:/odoo/links
      - ./odoo/script:/odoo/script
      - ./data/addons:/data/odoo/addons
      - ./data/filestore:/data/odoo/filestore
      - ./data/sessions:/data/odoo/sessions
    links:
      - db
    networks:
      - local
      - traefik
