services:
  kwkhtmltopdf:                                                                             
    image: acsone/kwkhtmltopdf                                                              
    networks:                                                                               
      - traefik
networks:
  traefik:
    external: true
version: '3.7'

