services:
  odoo:
    restart: always
    image: TODO
    environment:
      - MARABUNTA_MODE=prod
      - ADDONS_PATH=/odoo/links,/odoo/local-src,/odoo/src/odoo/addons,/odoo/src/addons
      - ODOO_BASE_URL=TODO
      - SENTRY=True
      - PGSSLMODE=require
      - DB_NAME=TODO
      - PGDATABASE=TODO
      - DB_USER=TODO
      - PGUSER=TODO
      - DB_HOST=TODO
      - PGHOST=TODO
    volumes:
      - ~/data/${COMPOSE_PROJECT_NAME}/addons:/data/odoo/addons
      - ~/data/${COMPOSE_PROJECT_NAME}/filestore:/data/odoo/filestore
      - ~/data/${COMPOSE_PROJECT_NAME}/sessions:/data/odoo/sessions
    ports:
      - 8069:8069
      - 8072:8072
version: '3.7'
