networks:
  local:
services:
  kwkhtmltopdf:
    image: acsone/kwkhtmltopdf
    networks:
      - local
  odoo:
    restart: always
    image: TODO
    environment:
      DB_HOST: $PGHOST
      DB_PORT: $PGPORT
      DB_PASSWORD: $PGPASSWORD
      DB_USER: $PGUSER
      DB_NAME: $PGDATABASE
      LOG_LEVEL: warn
      ODOO_BASE_URL: TODO
      PGSSLMODE: require
      RUNNING_ENV: prod
      SENTRY: True
    volumes:
      - ~/data/${COMPOSE_PROJECT_NAME}/addons:/data/odoo/addons
      - ~/data/${COMPOSE_PROJECT_NAME}/filestore:/data/odoo/filestore
      - ~/data/${COMPOSE_PROJECT_NAME}/sessions:/data/odoo/sessions
    ports:
      - 8069:8069
      - 8072:8072
    networks:
      - local
    links:
      - kwkhtmltopdf
version: "3.9"
