services:
  odoo:
    restart: always
    build: 
      context: odoo # at term, CI should build it for us
      args: 
        user: $ODOO_USER
        user_uid: $UID
        user_gid: $UID
    environment:
      - MARABUNTA_MODE=prod
      - ADDONS_PATH=/odoo/links,/odoo/local-src,/odoo/src/odoo/addons
      - ODOO_BASE_URL=
      - SENTRY=True
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${COMPOSE_PROJECT_NAME}.dev.akretion.com`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-long.rule=Host(`${COMPOSE_PROJECT_NAME}.dev.akretion.com`) && PathPrefix(`/longpolling/`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-long.tls=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.service=${COMPOSE_PROJECT_NAME}odoo"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-long.service=${COMPOSE_PROJECT_NAME}odoo_long"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}odoo.loadbalancer.server.port=8069"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}odoo_long.loadbalancer.server.port=8072"
    volumes:
      - ../data:/data/odoo/filestore
      - ../data:/data/odoo/sessions
      - ../data:/data/odoo/addons
version: '3.7'
