#!/bin/bash

if [ "$( psql -tAc "SELECT 1 FROM pg_database WHERE datname='$DB_NAME'" )" != '1' ]
then
    echo "Database does not exist, ignoring script"
    exit 0
fi

click-odoo-update --i18n-overwrite
