#!/bin/bash
set -e
python3 -m pip install pipx

# Install cli for all user
export PIPX_HOME=/opt/pipx PIPX_BIN_DIR=/usr/local/bin

pipx install git+https://github.com/akretion/ak --force --include-deps
# Force the version of git-aggregator in order to use git-autoshare
# TODO wait for this PR to be merged https://github.com/acsone/git-aggregator/pull/55
pipx inject ak git+https://github.com/Tecnativa/git-aggregator@use-git-autoshare --force
pipx install git-autoshare

pipx install manifestoo
pipx install coverage

git config --global user.email "bot@akretion.com"
git config --global user.name "Bot"
