#!/bin/bash

if [ "$( psql -tAc "SELECT 1 FROM pg_database WHERE datname='$DB_NAME'" )" != '1' ]
then
    echo "Database $DB_NAME does not exist, ignoring script"
    exit 0
fi

if [ "$( psql $DB_NAME -tAc "SELECT 1 FROM pg_tables WHERE tablename='ir_config_parameter'" )" != '1' ]
then
    echo "Database $DB_NAME not initialized, ignoring script"
    exit 0
fi

echo "START UPDATING USING MIGRATE"
# Migrate is an improved version of click odoo update
# see here : https://github.com/akretion/odoo-docker/blob/master/bin/migrate
migrate --i18n-overwrite
