FROM ghcr.io/akretion/odoo-docker:{{ odoo_version }}-latest as base

# syntax = docker/dockerfile:1.4

FROM base as prod

# Build and install odoo
COPY odoo-spec.yaml /odoo/odoo-spec.yaml
ENV BUILD_RESTRICT_LANG=fr.po
RUN --mount=type=cache,target=/root/.cache /install/build-odoo
RUN --mount=type=cache,target=/root/.cache pip install -e /odoo/src

# Build external source
COPY spec.yaml /odoo/spec.yaml
COPY frozen.yaml /odoo/frozen.yaml
RUN --mount=type=cache,target=/root/.cache /install/build-odoo-external
COPY ./requirements.txt /odoo/
RUN --mount=type=cache,target=/root/.cache cd /odoo && pip install -r requirements.txt

# Copy odoo config template
COPY ./templates /odoo/templates

# Copy local project
COPY ./start-entrypoint.d /odoo/start-entrypoint.d
COPY ./local-src /odoo/local-src
COPY ./scripts /odoo/scripts

FROM base as dev

COPY ./src /odoo/src
RUN --mount=type=cache,target=/root/.cache pip install -e /odoo/src
COPY ./requirements.txt /odoo/
RUN --mount=type=cache,target=/root/.cache pip install -r /odoo/requirements.txt
{% if provide_web_debugger %}RUN --mount=type=cache,target=/root/.cache pip install wdb{% endif %}
