# just aggregate this file name in COMPOSE_FILE key in .env file if you need this feature
version: "3.7"
services:
  odoo:
    links:
      - adminer
  adminer:
    image: adminer
    labels:
      - "docky.url_suffix=/?pgsql=db&username=odoo&db=db"
    environment:
      - ADMINER_PLUGINS=json-column tables-filter
      - ADMINER_DESIGN=rmsoft
    links:
      - db
    networks:
      - local
      - traefik
