networks:
  traefik:
    external: true
  local:
services:
  db:
    image: postgres:13
    user: "${UID}:${UID}"
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_DB=db
      - POSTGRES_PASSWORD=odoo
    volumes:
      - .db/:/var/lib/postgresql/data
    networks:
      - local
  odoo:
    build:
      context: odoo
      target: dev
    environment:
      PYTHONDONTWRITEBYTECODE: "True"
      PGDATABASE: db
      PGHOST: db
      PGPASSWORD: odoo
      PGUSER: odoo
      LIST_DB: "True"
      DB_FILTER: .*
      WITHOUT_DEMO: "False"
      WORKERS: 0
      ODOO_REPORT_URL: http://odoo:8069
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${COMPOSE_PROJECT_NAME}.localhost`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-long.rule=Host(`${COMPOSE_PROJECT_NAME}.localhost`)
        && PathPrefix(`/longpolling/`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.service=${COMPOSE_PROJECT_NAME}odoo"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-long.service=${COMPOSE_PROJECT_NAME}odoo_long"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}odoo.loadbalancer.server.port=8069"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}odoo_long.loadbalancer.server.port=8072"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}corsHeader.headers.accessControlAllowMethods=
        GET,POST,OPTIONS,PUT"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}corsHeader.headers.accessControlAllowOriginList=*"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}corsHeader.headers.accessControlAllowHeaders=DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,api-key,partner-email,authorization,sess-cart-id,website-unique-key"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}corsHeader.headers.accessControlExposeHeaders=Content-Length,Content-Range"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}corsHeader.headers.addVaryHeader=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.middlewares=${COMPOSE_PROJECT_NAME}corsHeader"
      - "docky.help=http://${COMPOSE_PROJECT_NAME}.localhost"
    links:
      - db
      - kwkhtmltopdf
    networks:
      - local
      - traefik
    volumes:
      - ./odoo:/odoo
      - ./data/addons:/data/odoo/addons
      - ./data/filestore:/data/odoo/filestore
      - ./data/sessions:/data/odoo/sessions
      - ./.home:/home/odoo # This directory is used for keeping the bash/psql history
  kwkhtmltopdf:
    image: acsone/kwkhtmltopdf
    networks:
      - local
version: "3.7"
